---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-gateway.yaml
  - namespace.yaml

namespace: hello

labels:
  - includeSelectors: true
    pairs:
      app: helloworld-gateway
