---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-watcher-rb
subjects:
  - kind: ServiceAccount
    name: configmap-watcher-sa
roleRef:
  kind: Role
  name: configmap-watcher-role
  apiGroup: rbac.authorization.k8s.io
