name: Kustomize & k8s manifest checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kustomize-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup kubectl (for kustomize)
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Render test overlay
      run: |
        mkdir -p build
        kubectl kustomize k8s/apps/hello-app/overlays/test > build/test.yaml

    - name: Render prod overlay
      run: kubectl kustomize k8s/apps/hello-app/overlays/prod > build/prod.yaml

    - name: Kubeval validate generated manifests
      run: |
        # install kubeval
        wget -qO /tmp/kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar -xzf /tmp/kubeval.tar.gz -C /tmp
        sudo mv /tmp/kubeval /usr/local/bin/
        kubeval --kubernetes-version="1.27.0" build/test.yaml build/prod.yaml

    - name: Kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        args: lint build/test.yaml build/prod.yaml