name: Python quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies & tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 yamllint pytest
        pip install -r apps/hello-app/src/requirements.txt
        pip install -r apps/configmap-watcher/src/requirements.txt

    - name: Run flake8 (apps/)
      run: flake8 apps || true

    - name: Run yamllint (k8s manifests)
      run: yamllint k8s || true

    - name: Run pytest (if tests present)
      run: pytest -q || true